import 'package:flutter/material.dart';
import '../../models/jobseeker/jobseeker_models.dart';
import '../../services/api_client.dart';
import '../../services/jobseeker/jobseeker_service.dart';
import '../../theme/app_theme.dart';

class JobSeekerDashboardScreen extends StatefulWidget {
  const JobSeekerDashboardScreen({super.key,required this.service,required this.onBrowseJobs});
  final JobSeekerService service; final VoidCallback onBrowseJobs;
  @override State<JobSeekerDashboardScreen> createState()=>_State();
}
class _State extends State<JobSeekerDashboardScreen>{
  JobSeekerDashboardStats? data; String? error; bool loading=true;
  @override void initState(){super.initState();_load();}
  Future<void> _load() async {setState(()=>loading=true);try{final d=await widget.service.getDashboard();if(mounted)setState((){data=d;error=null;});}on ApiException catch(e){if(mounted)setState(()=>error=e.message);}finally{if(mounted)setState(()=>loading=false);}}
  @override Widget build(BuildContext c){if(loading)return const Center(child:CircularProgressIndicator());if(error!=null)return _Error(message:error!,retry:_load);final d=data!;return RefreshIndicator(onRefresh:_load,child:ListView(padding:const EdgeInsets.all(16),children:[Text('Welcome, ${d.fullName.isEmpty?'Job Seeker':d.fullName}',style:Theme.of(c).textTheme.headlineSmall?.copyWith(fontWeight:FontWeight.w800)),const SizedBox(height:6),const Text('Track your progress and discover your next opportunity.',style:TextStyle(color:AppTheme.muted)),const SizedBox(height:18),GridView.count(crossAxisCount:2,shrinkWrap:true,physics:const NeverScrollableScrollPhysics(),crossAxisSpacing:12,mainAxisSpacing:12,childAspectRatio:1.20,children:[_Stat('Applications','${d.totalApplications}',Icons.assignment_rounded),_Stat('Active','${d.activeApplications}',Icons.timelapse_rounded),_Stat('Interviews','${d.interviewApplications}',Icons.event_available_rounded),_Stat('Available jobs','${d.availableJobs}',Icons.work_rounded)]),const SizedBox(height:16),_Card(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('Profile strength',style:TextStyle(fontWeight:FontWeight.w800,fontSize:16)),const SizedBox(height:10),LinearProgressIndicator(value:(d.profileCompleteness.clamp(0,100))/100),const SizedBox(height:8),Text('${d.profileCompleteness}% complete • ${d.skillsCount} skills • CV ${d.cvUploaded?'uploaded':'not uploaded'}',style:const TextStyle(color:AppTheme.muted)),const SizedBox(height:8),Text('Average skill match: ${d.averageMatchScore.toStringAsFixed(0)}%',style:const TextStyle(fontWeight:FontWeight.w600))])),if(d.topGapSkills.isNotEmpty)...[const SizedBox(height:16),_Card(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('Top skill gaps',style:TextStyle(fontWeight:FontWeight.w800,fontSize:16)),const SizedBox(height:10),Wrap(spacing:8,runSpacing:8,children:d.topGapSkills.map((s)=>Chip(label:Text(s))).toList())]))],const SizedBox(height:16),FilledButton.icon(onPressed:widget.onBrowseJobs,icon:const Icon(Icons.search_rounded),label:const Text('Browse available jobs'))]));}
}
class _Stat extends StatelessWidget{const _Stat(this.label,this.value,this.icon);final String label,value;final IconData icon;@override Widget build(BuildContext c)=>_Card(child:Column(crossAxisAlignment:CrossAxisAlignment.start,mainAxisAlignment:MainAxisAlignment.center,children:[Icon(icon,color:AppTheme.violet),const SizedBox(height:8),Text(value,style:const TextStyle(fontWeight:FontWeight.w900,fontSize:22)),const SizedBox(height:4),Flexible(child:Text(label,maxLines:2,overflow:TextOverflow.ellipsis,style:const TextStyle(color:AppTheme.muted,fontSize:12,height:1.2)))]));}
class _Card extends StatelessWidget{const _Card({required this.child});final Widget child;@override Widget build(BuildContext c)=>Container(padding:const EdgeInsets.all(16),decoration:BoxDecoration(color:Colors.white,border:Border.all(color:AppTheme.border),borderRadius:BorderRadius.circular(18)),child:child);}
class _Error extends StatelessWidget{const _Error({required this.message,required this.retry});final String message;final VoidCallback retry;@override Widget build(BuildContext c)=>Center(child:Padding(padding:const EdgeInsets.all(24),child:Column(mainAxisSize:MainAxisSize.min,children:[const Icon(Icons.cloud_off_rounded,size:42,color:AppTheme.muted),const SizedBox(height:12),Text(message,textAlign:TextAlign.center),const SizedBox(height:12),FilledButton(onPressed:retry,child:const Text('Retry'))])));}
