import 'package:flutter/material.dart';
import '../../models/jobseeker/jobseeker_models.dart';
import '../../services/api_client.dart';
import '../../services/jobseeker/jobseeker_service.dart';
import '../../theme/app_theme.dart';

class JobSeekerApplicationsScreen extends StatefulWidget{const JobSeekerApplicationsScreen({super.key,required this.service});final JobSeekerService service;@override State<JobSeekerApplicationsScreen> createState()=>_State();}
class _State extends State<JobSeekerApplicationsScreen>{List<JobSeekerApplication> apps=[];bool loading=true;String? error;String filter='All';
@override void initState(){super.initState();_load();}
Future<void> _load()async{setState(()=>loading=true);try{final a=await widget.service.getApplications();if(mounted)setState((){apps=a;error=null;});}on ApiException catch(e){if(mounted)setState(()=>error=e.message);}finally{if(mounted)setState(()=>loading=false);}}
Future<void> _withdraw(JobSeekerApplication a)async{final ok=await showDialog<bool>(context:context,builder:(c)=>AlertDialog(title:const Text('Withdraw application?'),content:Text('Withdraw your application for ${a.jobTitle}?'),actions:[TextButton(onPressed:()=>Navigator.pop(c,false),child:const Text('Cancel')),FilledButton(onPressed:()=>Navigator.pop(c,true),child:const Text('Withdraw'))]));if(ok!=true)return;try{await widget.service.withdraw(a.id);await _load();}on ApiException catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(e.message)));}}
@override Widget build(BuildContext c){final statuses=['All',...{for(final a in apps)a.status}];final shown=filter=='All'?apps:apps.where((a)=>a.status==filter).toList();return Column(crossAxisAlignment:CrossAxisAlignment.start,children:[SizedBox(height:52,child:ListView.separated(padding:const EdgeInsets.symmetric(horizontal:16,vertical:8),scrollDirection:Axis.horizontal,itemCount:statuses.length,separatorBuilder:(_,_)=>const SizedBox(width:7),itemBuilder:(_,i)=>ChoiceChip(label:Text(statuses[i]),selected:filter==statuses[i],onSelected:(_)=>setState(()=>filter=statuses[i])))),Expanded(child:loading?const Center(child:CircularProgressIndicator()):error!=null?Center(child:Text(error!)):shown.isEmpty?const Center(child:Text('No applications found.')):RefreshIndicator(onRefresh:_load,child:ListView.separated(padding:const EdgeInsets.all(16),itemCount:shown.length,separatorBuilder:(_,_)=>const SizedBox(height:10),itemBuilder:(_,i){final a=shown[i];return Card(child:Padding(padding:const EdgeInsets.all(15),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(children:[Expanded(child:Text(a.jobTitle,style:const TextStyle(fontWeight:FontWeight.w800,fontSize:16))),Chip(label:Text(a.status))]),Text(a.company,style:const TextStyle(color:AppTheme.muted)),const SizedBox(height:10),LinearProgressIndicator(value:(a.matchScore.clamp(0,100))/100),const SizedBox(height:5),Text('Skill match ${a.matchScore}%',style:const TextStyle(fontWeight:FontWeight.w600)),if(a.matchedSkills.isNotEmpty)...[const SizedBox(height:8),Text('Matched: ${a.matchedSkills.join(', ')}',style:const TextStyle(fontSize:12,color:Color(0xFF047857)))],if(a.gapSkills.isNotEmpty)...[const SizedBox(height:4),Text('Gaps: ${a.gapSkills.join(', ')}',style:const TextStyle(fontSize:12,color:Color(0xFFB45309)))],if(a.status.toLowerCase()=='applied')... [const SizedBox(height:10),Align(alignment:Alignment.centerRight,child:TextButton.icon(onPressed:()=>_withdraw(a),icon:const Icon(Icons.undo_rounded),label:const Text('Withdraw')))] ])));}))) ]);}}
