import 'package:flutter/material.dart';
import '../../models/recruiter/recruiter_requisition.dart';
import '../../services/api_client.dart';
import '../../services/hr/hr_service.dart';
import '../../theme/app_theme.dart';

class HrRequisitionsScreen extends StatefulWidget {
  const HrRequisitionsScreen({super.key, this.service}); final HrService? service;
  @override State<HrRequisitionsScreen> createState() => _HrRequisitionsScreenState();
}
class _HrRequisitionsScreenState extends State<HrRequisitionsScreen> {
  late final HrService _service = widget.service ?? HrService();
  List<RecruiterRequisition> _items = []; bool _loading = true; String? _error; String? _busyId;
  Future<void> _load() async { setState(() { _loading = true; _error = null; }); try { final x = await _service.getRequisitions(); if (mounted) setState(() { _items=x; _loading=false; }); } on ApiException catch(e){ if(mounted)setState((){_error=e.message;_loading=false;}); } }
  @override void initState(){super.initState();_load();}
  Future<void> _approve(RecruiterRequisition r) async { setState(()=>_busyId=r.id); try { await _service.approveRequisition(r.id); await _load(); if(mounted) ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('Requisition approved.'))); } on ApiException catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text(e.message)));} finally {if(mounted)setState(()=>_busyId=null);} }
  Future<void> _reject(RecruiterRequisition r) async { final c=TextEditingController(); final reason=await showDialog<String>(context:context,builder:(ctx)=>AlertDialog(title:const Text('Reject requisition'),content:TextField(controller:c,minLines:3,maxLines:5,decoration:const InputDecoration(hintText:'Reason for rejection')),actions:[TextButton(onPressed:()=>Navigator.pop(ctx),child:const Text('Cancel')),FilledButton(onPressed:()=>Navigator.pop(ctx,c.text.trim()),child:const Text('Reject'))])); c.dispose(); if(reason==null)return; if(reason.length<5){if(mounted)ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Please provide a clear reason (at least 5 characters).')));return;} setState(()=>_busyId=r.id); try{await _service.rejectRequisition(r.id,reason);await _load();if(mounted)ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Requisition rejected.')));}on ApiException catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(e.message)));}finally{if(mounted)setState(()=>_busyId=null);} }
  @override Widget build(BuildContext context)=>RefreshIndicator(onRefresh:_load,color:const Color(0xFF059669),child:ListView(physics:const AlwaysScrollableScrollPhysics(),padding:const EdgeInsets.fromLTRB(20,20,20,32),children:[Text('Requisition approvals',style:Theme.of(context).textTheme.headlineMedium),const SizedBox(height:8),Text('Review recruiter requests and approve or reject submitted positions.',style:Theme.of(context).textTheme.bodyMedium),const SizedBox(height:22),if(_loading)const Center(child:Padding(padding:EdgeInsets.all(60),child:CircularProgressIndicator()))else if(_error!=null)Text(_error!,style:const TextStyle(color:Colors.red))else if(_items.isEmpty)const _Empty()else ..._items.map(_card)]));
  Widget _card(RecruiterRequisition r){final pending=r.status==RequisitionStatus.submitted;final busy=_busyId==r.id;return Card(margin:const EdgeInsets.only(bottom:12),elevation:0,shape:RoundedRectangleBorder(borderRadius:BorderRadius.circular(20),side:const BorderSide(color:AppTheme.border)),child:Padding(padding:const EdgeInsets.all(17),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(children:[Expanded(child:Text(r.positionTitle,style:const TextStyle(fontSize:17,fontWeight:FontWeight.w800))),_Status(status:r.status)]),const SizedBox(height:8),Text('${r.department} • ${r.location}',style:const TextStyle(color:AppTheme.muted)),const SizedBox(height:8),Text('Recruiter: ${r.recruiterName}'),Text('Headcount: ${r.headcount} • ${r.employmentType.label} • ${r.workMode.label}'),const SizedBox(height:6),Text(r.salaryRangeFormatted,style:const TextStyle(fontWeight:FontWeight.w600)),if((r.justification??'').trim().isNotEmpty)...[const SizedBox(height:10),Text('Justification: ${r.justification}',style:const TextStyle(fontSize:13,color:AppTheme.muted))],if(pending)...[const SizedBox(height:16),Row(children:[Expanded(child:OutlinedButton(onPressed:busy?null:()=>_reject(r),child:const Text('Reject'))),const SizedBox(width:10),Expanded(child:FilledButton(style:FilledButton.styleFrom(backgroundColor:const Color(0xFF059669)),onPressed:busy?null:()=>_approve(r),child:busy?const SizedBox(width:18,height:18,child:CircularProgressIndicator(strokeWidth:2,color:Colors.white)):const Text('Approve')))])]])));
  }
}
class _Status extends StatelessWidget{const _Status({required this.status});final RequisitionStatus status;@override Widget build(BuildContext context){final approved=status==RequisitionStatus.approved;final rejected=status==RequisitionStatus.rejected;final color=approved?const Color(0xFF047857):rejected?const Color(0xFFB91C1C):const Color(0xFFB45309);final bg=approved?const Color(0xFFECFDF5):rejected?const Color(0xFFFEF2F2):const Color(0xFFFFFBEB);return Container(padding:const EdgeInsets.symmetric(horizontal:9,vertical:5),decoration:BoxDecoration(color:bg,borderRadius:BorderRadius.circular(14)),child:Text(status.label,style:TextStyle(fontSize:11,fontWeight:FontWeight.w700,color:color)));}}
class _Empty extends StatelessWidget{const _Empty();@override Widget build(BuildContext context)=>const Padding(padding:EdgeInsets.symmetric(vertical:70),child:Column(children:[Icon(Icons.inbox_outlined,size:46,color:AppTheme.muted),SizedBox(height:12),Text('No company requisitions found.',style:TextStyle(color:AppTheme.muted))]));}
